apps/authapp/views.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash
from flask_login import login_user
from sqlalchemy import select
from apps.authapp import forms 
from apps import models 
from apps.app import migrate, Session

authapp = Blueprint(
    'authapp',
    __name__,
    template_folder='templates_auth',
    static_folder='static_auth',
    )


@authapp.route('/', methods=['GET', 'POST'])
def index():
    form = forms.LoginForm()
    if form.validate_on_submit():
        try:
            session = Session()
            stmt = select(models.User).filter_by(email=form.email.data).limit(1)
            user = session.execute(stmt).scalars().first()
            if user is not None and user.verify_password(form.password.data):
                login_user(user)
                session.close()
                return redirect(url_for('pictapp.index'))
            else:
                flash("メールアドレスまたはパスワードが正しくありません")
        except Exception as e:
            flash("ログイン時にエラーが発生しました")
            print(f"Error during login: {e}")
        finally:
            session.close()
    return render_template('login.html', form=form)

apps/templates/index.html
<!DOCTYPE html>

<html lang="ja">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Start Share Spotify Playlist</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='assets/favicon.ico')}}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
        rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet" />
</head>

<body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#page-top">Start Share Playlist</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#about">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#services">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">Sign-up</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <header class="masthead">
        <div class="container px-4 px-lg-5 h-100">
            <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-8 align-self-end">
                    <h1 class="text-white font-weight-bold">
                        Let's Share Your Favorite Playlist</h1>
                    <hr class="divider" />
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="text-white-75 mb-5">
                        自分のお気に入りのプレイリストをみんなに共有しよう!
                    </p>
                    <a class="btn btn-primary btn-xl" href="#about">Find Out More</a>
                </div>
            </div>
        </div>
    </header>
    <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="text-white mt-0">Here is login screen!</h2>
                    <hr class="divider divider-light" />
                    <p class="text-white-75 mb-4">
                        ユーザー登録はお済みですか?
                    </p>
                    <a class="btn btn-light btn-xl" href="#services">
                        Get Started!</a>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section" id="services">
        <div class="container px-4 px-lg-5">
            <h2 class="text-center mt-0">このアプリの流れ</h2>
            <hr class="divider" />
            <div class="row gx-4 gx-lg-5">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">ユーザー登録</h3>
                        <p class="text-muted mb-0">メールアドレスとパスワードを設定して、アカウントを作ろう!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">ログイン</h3>
                        <p class="text-muted mb-0">作ったアカウントにログインしてマイページをみてみよう</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-globe fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">プレイリストを投稿</h3>
                        <p class="text-muted mb-0">共有機能でプレイリストを共有しよう</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-heart fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">いろんなプレイリストを楽しもう!</h3>
                        <p class="text-muted mb-0">他の人が投稿しているプレイリストも見ながら音楽を楽しもう！</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="page-section bg-dark text-white" id="login">
        <div class="container px-4 px-lg-5 text-center">
            <h2 class="mb-4">Login here!</h2>
            <a class="btn btn-light btn-xl"
                href="{{url_for('authapp.index')}}">Login Now!</a>
        </div>
    </section>
<section class="page-section" id="contact">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 col-xl-6 text-center">
                <h2 class="mt-0">新規登録はこちら</h2>
                <hr class="divider" />
                <p class="text-muted mb-5">ここでは新しくアカウントを作成することができます。</p>
            </div>
        </div>
        <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
            <div class="col-lg-6">
                <form action="{{url_for('signup')}}"
                        method="POST"
                        novalidate="novalidate">
                    {% for message in get_flashed_messages() %}
                    <p style="color:red">{{ message }}</p>
                    {% endfor %}
                    {{form.csrf_token}}
                    <p>
                        {{form.username.label}}
                        {{form.username(placeholder="ユーザー名")}}
                        {% for error in form.username.errors %}
                        <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.email.label}}
                        {{form.email(placeholder="メールアドレス")}}
                        {% for error in form.email.errors %}
                        <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.password.label}}
                        {{form.password(placeholder="パスワード")}}
                        {% for error in form.password.errors %}
                        <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.submit()}}
                    </p>
                </form>
            </div>
        </div>
    </div>
</section>
    <footer class="bg-light py-5">
        <div class="container px-4 px-lg-5">
            <div class="small text-center text-muted">
                Copyright &copy; 2023 - Picture Post App
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <script src="{{url_for('static', filename='js/scripts.js')}}"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>